import type { RunMetadata } from '../tracking/run.js';
import type { Metrics } from '../metrics/effects.js';
import type { GateEvaluation } from '../gates/evaluator.js';

export function generateReport(
  metadata: RunMetadata,
  metrics: Metrics,
  gateEvaluation: GateEvaluation
): string {
  const lines: string[] = [];

  lines.push('# HireGauge Audit Report');
  lines.push('');
  lines.push('## Run Summary');
  lines.push('');
  lines.push(`- **Run ID**: ${metadata.runId}`);
  lines.push(`- **Timestamp**: ${metadata.timestamp}`);
  lines.push(`- **Model**: ${metadata.model.provider}/${metadata.model.name} (temp=${metadata.model.temperature})`);
  lines.push(`- **Mode**: ${metadata.mode}`);
  lines.push(`- **Profiles**: ${metadata.profileCount}`);
  lines.push(`- **Repetitions**: ${metadata.repetitions}`);
  lines.push(`- **Total Evaluations**: ${metrics.totalEvaluations}`);
  lines.push(`- **Successful**: ${metrics.successfulEvaluations}`);
  lines.push(`- **Failed**: ${metrics.failedEvaluations}`);
  lines.push(`- **Prompt Version**: ${metadata.promptVersion}`);
  if (metadata.gitCommit) {
    lines.push(`- **Git Commit**: ${metadata.gitCommit.substring(0, 8)}`);
  }
  lines.push('');

  lines.push('## Quality Gates');
  lines.push('');
  lines.push(`**${gateEvaluation.summary}**`);
  lines.push('');
  for (const result of gateEvaluation.results) {
    const icon = result.passed ? '✅' : '❌';
    lines.push(`- ${icon} ${result.message}`);
  }
  lines.push('');

  lines.push('## Main Effects');
  lines.push('');
  lines.push('*What signals does the model prioritize?*');
  lines.push('');
  lines.push('| Factor | Effect Size | Top Level | Mean Score |');
  lines.push('|--------|-------------|-----------|------------|');
  for (const effect of metrics.mainEffects) {
    const topLevel = effect.levels.reduce((a, b) => (a.meanScore > b.meanScore ? a : b));
    lines.push(
      `| ${effect.factor} | ${effect.effectSize.toFixed(3)} | ${topLevel.level} | ${topLevel.meanScore.toFixed(2)} |`
    );
  }
  lines.push('');

  for (const effect of metrics.mainEffects) {
    lines.push(`### ${effect.factor}`);
    lines.push('');
    for (const level of effect.levels) {
      lines.push(`- **${level.level}**: ${level.meanScore.toFixed(2)} (n=${level.count})`);
    }
    lines.push('');
  }

  lines.push('## Interaction Effects');
  lines.push('');
  lines.push('*Do evaluation standards change across groups?*');
  lines.push('');

  if (metrics.interactionEffects.length === 0) {
    lines.push('No demographic factor found for interaction analysis.');
  } else {
    for (const interaction of metrics.interactionEffects) {
      const [factorA, factorB] = interaction.factors;
      lines.push(`### ${factorA} × ${factorB}`);
      lines.push('');
      lines.push(`**Effect Size**: ${interaction.effectSize.toFixed(3)}`);
      lines.push('');
      lines.push(interaction.description);
      lines.push('');
      lines.push('| Combination | Mean Score | Count |');
      lines.push('|-------------|------------|-------|');
      for (const [key, cell] of Object.entries(interaction.cells)) {
        lines.push(`| ${key.replace('|', ' / ')} | ${cell.meanScore.toFixed(2)} | ${cell.count} |`);
      }
      lines.push('');
    }
  }

  lines.push('## Variance Analysis');
  lines.push('');
  lines.push('*How stable are the results across runs?*');
  lines.push('');
  lines.push(`- **Mean Std Dev**: ${metrics.varianceSummary.overallMeanVariance.toFixed(3)}`);
  lines.push(`- **Max Std Dev**: ${metrics.varianceSummary.maxVariance.toFixed(3)}`);
  lines.push(`- **Unstable Profiles**: ${metrics.varianceSummary.unstableCount}`);
  lines.push('');

  if (metrics.varianceSummary.unstableProfiles.length > 0) {
    lines.push('### Unstable Profiles');
    lines.push('');
    lines.push('The following profiles showed high variance across repetitions:');
    lines.push('');
    for (const profileId of metrics.varianceSummary.unstableProfiles) {
      const pv = metrics.perProfileStats.find((p) => p.profileId === profileId);
      if (pv) {
        lines.push(`- **${profileId}**: mean=${pv.mean.toFixed(2)}, stdDev=${pv.stdDev.toFixed(3)}`);
      }
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Report generated by HireGauge*');

  return lines.join('\n');
}
